services:
  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_PASSWORD=p@ssw0rd
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    networks:
      - hub
  api:
    image: "node:lts-buster"
    volumes:
      - ./api/:/app
    working_dir: "/app"
    command: ["npx", "nodemon", "src/index.ts"]
    networks:
      - hub
    ports:
      - 3000:3000
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=p@ssw0rd
networks:
  hub:
